run:
  timeout: 5m

linters:
  enable:
    - staticcheck
    - gosec
    - govet
    - revive
    - errcheck
    - ineffassign
    - unused
    - gocritic
    - dupl
    - gocyclo
    - gofmt
    - goimports

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  revive:
    rules:
      - name: exported
        disabled: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
